### ISSUE TITLE
Clarification: issue regarding encoding meta tokens

### ISSUE THREAD

**Issue by tannonk** [google/sentencepiece#624] opened 2021-02-10 15:08 UTC
Hi, 

Apologies in advance for what may be a dumb question, but I'm having some trouble understanding exactly what the purpose of the special tokens `<s>`, `</s>`, `<unk>` is.

For example, if I try to encode a string containing one of these symbols it gets split up.

```
import sentencepiece as spm
sp = spm.SentencePieceProcessor(model_file=str('./python/test/test_model.model'))
print(sp.encode_as_pieces("<s> help ! </s>"))
>>> ['▁', '<', 's', '>', '▁help', '▁', '!', '▁', '</', 's', '>']
```

I would have expected the tokens `<s>` and `</s>` to remain unsplit since they are encoded in the model, e.g. `['▁', '<s>', '▁help', '▁', '!', '▁', '</s>']`.

Could you please clarify why this happens?

**Comment by taku910** [comment] 2021-02-11 08:11
Duplicate of #215

**Closed by taku910** 2021-02-11 08:11 UTC
