### ISSUE TITLE
Question: fail to construct SentencePieceProcessor in cpp

### ISSUE THREAD

**Issue by zhangguanheng66** [google/sentencepiece#592] opened 2020-12-03 19:01 UTC
I create a wrapper cpp class for `sentencepiece::SentencePieceProcessor` ([here](https://github.com/zhangguanheng66/text/blob/54388c4c5f314c6bddafbdb9192b6ee73f3d60b0/torchtext/csrc/sentencepiece.cpp#L5-L11)) and when I call the constructor in pybind11 `py::pickle` ([link](https://github.com/zhangguanheng66/text/blob/sp_binding/torchtext/csrc/register_bindings.cpp#L72)), it reports error that `‘sentencepiece::SentencePieceProcessor::SentencePieceProcessor(const sentencepiece::SentencePieceProcessor&)’ is implicitly deleted because the default definition would be ill-formed`.  Any ideas?

The full error message is here
```
FAILED: /private/home/zhangguanheng/tmp/PyTorch/text/build/temp.linux-x86_64-3.7/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.o
c++ -MMD -MF /private/home/zhangguanheng/tmp/PyTorch/text/build/temp.linux-x86_64-3.7/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.o.d -pthread -B /private/home/zhangguanheng/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc -I/private/home/zhangguanheng/tmp/PyTorch/text/third_party/build/include -I/private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include -I/private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/torch/csrc/api/include -I/private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/TH -I/private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/THC -I/private/home/zhangguanheng/anaconda3/include/python3.7m -c -c /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp -o /private/home/zhangguanheng/tmp/PyTorch/text/build/temp.linux-x86_64-3.7/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_torchtext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp: In lambda function:
/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp:72:39: error: use of deleted function ‘torchtext::SentencePiece::SentencePiece(torchtext::SentencePiece&&)’
             return SentencePiece(state);
                                       ^
In file included from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp:5:0:
/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/sentencepiece.h:7:8: note: ‘torchtext::SentencePiece::SentencePiece(torchtext::SentencePiece&&)’ is implicitly deleted because the default definition would be ill-formed:
 struct SentencePiece : torch::CustomClassHolder {
        ^~~~~~~~~~~~~
/private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/sentencepiece.h:7:8: error: use of deleted function ‘sentencepiece::SentencePieceProcessor::SentencePieceProcessor(const sentencepiece::SentencePieceProcessor&)’
In file included from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/sentencepiece.h:1:0,
                 from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp:5:
/private/home/zhangguanheng/tmp/PyTorch/text/third_party/build/include/sentencepiece_processor.h:168:7: note: ‘sentencepiece::SentencePieceProcessor::SentencePieceProcessor(const sentencepiece::SentencePieceProcessor&)’ is implicitly deleted because the default definition would be ill-formed:
 class SentencePieceProcessor {
       ^~~~~~~~~~~~~~~~~~~~~~
/private/home/zhangguanheng/tmp/PyTorch/text/third_party/build/include/sentencepiece_processor.h:168:7: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = sentencepiece::ModelInterface; _Dp = std::default_delete<sentencepiece::ModelInterface>]’
In file included from /usr/include/c++/7/memory:80:0,
                 from /private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/pybind11/detail/common.h:160,
                 from /private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/pybind11/pytypes.h:12,
                 from /private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/pybind11/cast.h:13,
                 from /private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/pybind11/attr.h:13,
                 from /private/home/zhangguanheng/tmp/PyTorch/pytorch/torch/include/pybind11/pybind11.h:45,
                 from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp:1:
/usr/include/c++/7/bits/unique_ptr.h:388:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
In file included from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/sentencepiece.h:1:0,
                 from /private/home/zhangguanheng/tmp/PyTorch/text/torchtext/csrc/register_bindings.cpp:5:
/private/home/zhangguanheng/tmp/PyTorch/text/third_party/build/include/sentencepiece_processor.h:168:7: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = sentencepiece::normalizer::Normalizer; _Dp = std::default_delete<sentencepiece::normalizer::Normalizer>]’
 class SentencePieceProcessor {
       ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by taku910** [comment] 2021-01-10 06:45
Could you provide a minimum set of code/command line to reproduce this error?  It is hard to see the root cause only with this information.

**Comment by xiefangqi** [comment] 2021-12-07 02:53
@zhangguanheng66 Can this problem reproduce again?  I tryed with:
git clone https://github.com/pytorch/text torchtext
cd torchtext
git checkout -b sp_binding origin/sp_binding
git submodule update --init --recursive
python setup.py clean install

In this way, the compilation is successful. This commit https://github.com/zhangguanheng66/text/blob/54388c4c5f314c6bddafbdb9192b6ee73f3d60b0/torchtext/csrc/sentencepiece.cpp#L5-L11 does not exist.

**Comment by taku910** [comment] 2022-05-29 04:27
Please let me close this bug, as we already have the steps to compile the bindings successfully.

**Closed by taku910** 2022-05-29 04:27 UTC
Labels: help wanted
