### ISSUE TITLE
No module named '_sentencepiece'

### ISSUE THREAD

**Issue by ayusharora99** [google/sentencepiece#472] opened 2020-03-27 01:26 UTC
I am trying to import sentencepiece to my jupyter notebook but I am running into an error on this line:

`import tokenization` 

because of this line in sentencepiece.py:

`return importlib.import_module('_sentencepiece')`

This is the error:

No module named '_sentencepiece'

**Comment by taku910** [comment] 2020-04-23 02:02
Sorry, could you elaborate the error? it is hard to reproduce this error.

**Comment by taku910** [comment] 2020-04-24 14:28
Let me close this bug, because this code doesn't follow the official instruction of sentencepiece.

**Closed by taku910** 2020-04-24 14:28 UTC
Labels: execution environment
