### ISSUE TITLE
Very slow training on AMD CPU

### ISSUE THREAD

**Issue by kjhanjee** [google/sentencepiece#887] opened 2023-06-25 16:55 UTC
Hi All, 

I've been trying to train a BPE tokenizer with the following options. The data is around 300+ GB of text. 

`spm.SentencePieceTrainer.Train('--input={} --model_prefix=tokener --unk_piece=[UNK] --pad_piece=[PAD] --bos_piece=[CLS] --eos_piece=[SEP] --user_defined_symbols=[PAD],[MASK],[END_GEN] --vocab_size=110000 --input_sentence_size=15000000 --num_threads=1000'.format(file_paths),num_threads=1000)`

My system specs are as below - 

CPU - AMD 5600X 
RAM 32 GB 3200 MHz 

The training has been going on for almost 2 1/2 hrs and still hasn't completed. My CPU utilization is only at 13%. Not sure if this is the expected behavior or there is some room for improvement.

**Comment by dgrahn** [comment] 2023-07-12 22:11
I'm not an expert on this project. But 1000 threads is far too many for a single CPU. That processor supports running 12 threads at a time. So to use more than 12 threads, the CPU has to switch between them.

Try setting your `num_threads` to 6 or 12. I wouldn't be surprised if that helps.

**Comment by kjhanjee** [comment] 2023-07-12 23:24
I've tried setting it to many different values including 12 with no help. The cpu usage wasn't going beyond 13-17%. I instead switched to hf bpe trainer. Still took me over 16hrs to rain

**Comment by Goader** [comment] 2023-08-17 00:47
@kjhanjee Can it be that most of the time Sentencepiece simply traverses through your data sampling 15m sentences you have specified in the `input_sentence_size` parameter? Have you seen the first merges appearing in the logs?

**Comment by kjhanjee** [comment] 2023-08-17 05:35
It completed training but took 16 hrs to complete. The problem isn't the number of sentences. It is parallel execution. While computing merges as well it only utilizes 16% of my cpu. I switched to hf tokenizer to train bpe though even that seems to be taking a lot of time about 10 hrs. Could be because I'm keeping a huge vocabulary size.

**Comment by taku910** [comment] 2023-12-23 08:28
In general, larger corpus/vocab sizes require a lot of time. We don't know the cause of the problem just from the current reports, and we can't determine if it's AMD-specific or not.

**Comment by taku910** [comment] 2024-02-26 11:31
We are going to close this issue on March 1 if there are not further updates.

**Closed** 2024-03-11 11:31 UTC
