### ISSUE TITLE
error while installing sentencepiece  python 3.12.2

### ISSUE THREAD

**Issue by mistrytejasm** [google/sentencepiece#976] opened 2024-02-19 09:34 UTC
PS D:\Text Summarization\Text-Summarization> pip install sentencepiece             
Collecting sentencepiece
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mistr\AppData\Local\Temp\pip-install-lotemg9m\sentencepiece_26977f4d58994047ad8c0ab1707422de\setup.py", line 126, in <module>
          subprocess.check_call([
        File "C:\Users\mistr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mistr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mistr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\mistr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by severinsimmler** [comment] 2024-02-19 09:37
Duplicate of https://github.com/google/sentencepiece/issues/932 and will be fixed in the next release. You can install the pre-release from GitHub until officially released on PyPI (or use Python 3.11): https://github.com/google/sentencepiece/releases/tag/v0.2.0pre1

**Comment by taku910** [comment] 2024-02-19 17:10
Duplicate of https://github.com/google/sentencepiece/issues/932

**Closed by taku910** 2024-02-19 17:10 UTC
