### ISSUE TITLE
Segmentation fault (core dumped) on Centos

### ISSUE THREAD

**Issue by omrivm** [google/sentencepiece#597] opened 2020-12-11 19:43 UTC
When i install sentencepiece (0.1.91) on Centos i get "Segmentation fault (core dumped)".
Dose sentencepiece supports Centos 7? or i'm doing something wrong?

**Comment by taku910** [comment] 2020-12-20 01:16
Could you elaborate the report so we can reproduce? Ho
How did you install or run sentencepiece?, python version, and other pip libraries executed with sentencepiece.

**Comment by xiefangqi** [comment] 2021-12-07 03:08
@omrivm Hello, Can this issue reproduce again? Can the installation methods and test cases be provided?

**Comment by omrivm** [comment] 2021-12-07 07:54
@xiefangqi i don't have access to this machine anymore to reproduce the issue.

**Comment by taku910** [comment] 2022-05-29 04:14
Please let me close this issue since there seems to be no further discussion

**Closed by taku910** 2022-05-29 04:14 UTC
Labels: help wanted
