### ISSUE TITLE
issue using tf-sentencepiece with tf2 tf.data.Datasets

### ISSUE THREAD

**Issue by terrykong** [google/sentencepiece#430] opened 2019-12-09 19:21 UTC
Hi guys,

I'm wondering if this is a bug or if a workaround exists. I'm using sentencepiece in tf 2.0 and I only come across a segfault when using sentencepiece with tf.data.Datasets

For my environment, I am using a docker image (`tensorflow/tensorflow:2.0.0-py3`) and using the 0.1.84 wheel built on https://github.com/google/sentencepiece/releases, i.e., `tf_sentencepiece-0.1.84-py2.py3-none-manylinux1_x86_64.whl`

So this works
```python
import tensorflow as tf
import tf_sentencepiece as tfs
sentencepiece_model_file = # any sentencepiece model
print(tfs.encode(['hello'], model_proto=open(sentencepiece_model_file,'rb').read()))
```

But this doesn't
```python
import tensorflow as tf
import tf_sentencepiece as tfs
sentencepiece_model_file = # any sentencepiece model
dataset = tf.data.Dataset.from_tensor_slices(['hello', 'world']);
dataset = dataset.map(lambda line: tfs.encode([line], model_proto=open(sentencepiece_model_file,'rb').read()))  # ERRORS HERE (Segmentation fault (core dumped))
for item in dataset:
    print(item)
```

Thanks!

**Comment by jjedele** [comment] 2020-03-04 15:46
Seeing the some problem right now. Only on linux though interestingly, on my Mac it works.

**Comment by jjedele** [comment] 2020-03-04 15:57
My example to reproduce (basically the same as above):

```python
import tensorflow as tf
import tf_sentencepiece

bpe_model_path = tf.keras.utils.get_file("bpe_en_50k.model", "https://nlp.h-its.org/bpemb/en/en.wiki.bpe.vs50000.model")

# works
tokens = tf_sentencepiece.encode(["Hello World"], model_file=bpe_model_path)

print(tokens)

ds = tf.data.Dataset.from_tensors("Hello World")

# segfaults
ds = ds.map(lambda x: tf_sentencepiece.encode(x, model_file=bpe_model_path))

for i in ds:
    print(i)
```

**Comment by jjedele** [comment] 2020-03-04 16:06
Ugly workaround (probably slow):

```python
def bpe_encode_workaround(model_path):
    def encode(x):
        encoded = tf_sentencepiece.encode([x], model_file=model_path)
        return encoded.values

    return lambda x: tf.py_function(encode, [x], tf.int32)

ds = ds.map(bpe_encode_workaround(model_path))
```

**Comment by jjedele** [comment] 2020-03-04 18:19
Ok, so I just set up my environment to see if I can fix the problem. Turns out simply rebuilding the libraries fixed the problem. So it must be related to the build/release rather than a bug in the code.

**Comment by taku910** [comment] 2020-10-13 04:43
tf-sentencepiece is removed from the repos, because tf.text supports sentencepiece. Let me close this issue.

**Closed by taku910** 2020-10-13 04:43 UTC
Labels: execution environment
