### ISSUE TITLE
protobuf Deprecation Warnings

### ISSUE THREAD

**Issue by jlowryduda** [google/sentencepiece#590] opened 2020-12-02 19:01 UTC
Hi!

I've been using `sentencepiece_pb2.py`, which requires `protobuf`. Recently I've noticed that there are deprecation warnings logged for `FileDescriptor`, `FieldDescriptor`, and `Descriptor` (which are used in `sentencepiece_pb2.py`). The warnings look like this:

> DeprecationWarning: Call to deprecated create function FileDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.

Is there a chance you'd want to fix it?

**Comment by taku910** [comment] 2020-12-21 09:04
Duplicate of #595

**Closed** 2020-12-21 09:04 UTC
