### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(890)

### ISSUE THREAD

**Issue by aahad5555** [google/sentencepiece#736] opened 2022-03-16 11:51 UTC
Having this issue in preprocessing everything looks fine but the problem still exists!!!

**Comment by taku910** [comment] 2022-03-19 15:58
Let me close this bug due to lack of specific information and inability to reproduce.

**Closed by taku910** 2022-03-19 15:58 UTC

**Comment by aahad5555** [comment] 2022-03-21 07:57
> Let me close this bug due to lack of specific information and inability to reproduce.

I provided the issue with full reference but it seems deleted now... why?? It appears the model is not available on hugging face either now.
