### ISSUE TITLE
Word based algorithm in SentencePiece is not being able to preserve some character in Devanagiri

### ISSUE THREAD

**Issue by sanjibnarzary** [google/sentencepiece#442] opened 2020-01-15 20:41 UTC
The sentence piece provides four algorithm for training the tokenizer. BPE, char, unigram and word. Among these all are performing well however the BLEU score while testing on word based tokenization giving very bad result on test data. This is also the same case with huggingface BertWordPiece tokenizer.

I have tested it on Bodo text which is written in Devanagiri script. I hope this problem will be there in Hindi, Marathi or other Indian languages using Devanagiri scripts.

I have uploaded the tokenizer model file in my page if you need to verify https://github.com/sanjibnarzary/bodo-tokenizers

**Comment by taku910** [comment] 2020-01-16 11:48
Sentencepiece does normalize the input with NFKC. 
https://github.com/google/sentencepiece/blob/master/data/nmt_nfkc.tsv is the normalization table.

Please check there is a character replacement table in this file.

In addition, you can disable NFKC normalization by ```spm_train ... --normalization_rule_name=identity``` 

https://github.com/google/sentencepiece/blob/master/doc/normalization.md

**Comment by sanjibnarzary** [comment] 2020-01-17 04:17
Dear @taku910 Thank you for the reply.
Let me check with `nfkc`. One question does the nfc normalization should be done to the raw training data or during training supplied along with spm_train as parameter.

**Comment by sanjibnarzary** [comment] 2020-01-17 12:53
I have done the with the `--normalization_rule_name=nmt_nfkc` during training, however it did not improve the BLEU score. Then I tried with `--normalization_rule_tsv=nmt_nfkc.tsv` but it gives me error.
```
builder.cc(483) LOG(INFO) Loading maping file: 
..truncated../datas/nmt_nfkc.tsv
builder.cc(494) [(fields.size()) >= (1)] 
Program terminated with an unrecoverable error.
```

**Comment by taku910** [comment] 2020-04-23 03:11
I could not reproduce the warning. Could you double check  `nmt_nfkc.tsv` is correct?

**Comment by taku910** [comment] 2022-08-07 08:35
Let me close this bug as there is no update from 23 Apr 2020.

**Closed by taku910** 2022-08-07 08:35 UTC
Labels: help wanted
