### ISSUE TITLE
python 3.7 does not work 

### ISSUE THREAD

**Issue by r-wheeler** [google/sentencepiece#381] opened 2019-08-22 19:15 UTC
In a Python 3.7.4 environment: 
```
pip install tensorflow==1.13.1
pip install tf_sentencepiece
```
```
>>>import tf_sentencepiece 

 ---> Running in 6ee6c76782ac
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/usr/local/lib/python3.7/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 43, in <module>
    _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.13.1: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by sooneecheah** [comment] 2019-10-30 10:23
@r-wheeler @gobrewers14 I've had a look at this and it looks like this might not be caused by Sentencepiece, but rather tensorflow. 

It looks like the Tensorflow 1.14 wheel for python 3.7 is compiled with `-D_GLIBCXX_USE_CXX11_ABI=1`, which is rather unusual for Tensorflow. This is causing issues as compiling SentencePiece with `-DSPM_ENABLE_TENSORFLOW_SHARED=ON` will set `-D_GLIBCXX_USE_CXX11_ABI` to 0, rather than 1. This causes the invalid symbol error when attempting to load the `.so` file, as the protobuf library that was statically linked into sentencepiece was done using the pre-C++ 11 ABI, while Tensorflow is looking for C++ 11 ABI symbols. (that's my understanding anyway)

I got around this problem by 

- compiling and installing protobuf 3.7 with `-D_GLIBCXX_USE_CXX11_ABI=1` (the default).
- modifying the `make_py_wheel.sh` script in this repo to remove `-DSPM_ENABLE_TENSORFLOW_SHARED=ON` and add `-DSPM_USE_BUILTIN_PROTOBUF=OFF` to the `cmake` command on line 68.
- the wheel that comes out in `dist/` should work with tensorflow 1.14 in python 3.7
- Curiously, the solution to this problem is the opposite to the solution for getting Tensorflow Serving to run with SentencePiece 🤷‍♂

**Comment by taku910** [comment] 2020-04-24 14:15
Let me close this bug as the latest release only supports tensorflow >= 1.5.0. Please reopen this bug if you find similar issues again.

**Closed by taku910** 2020-04-24 14:15 UTC
