### ISSUE TITLE
pip subprocess to install build dependencies did not run successfully. │ exit code: 1

### ISSUE THREAD

**Issue by Anubiiss** [google/sentencepiece#989] opened 2024-03-21 12:32 UTC
`C:\Users\Ali>pip install esptool
Collecting esptool
  Using cached esptool-4.7.0.tar.gz (285 kB)
  Preparing metadata (setup.py) ... done
Collecting bitstring>=3.1.6 (from esptool)
  Using cached bitstring-4.1.4-py3-none-any.whl.metadata (5.8 kB)
Collecting cryptography>=2.1.4 (from esptool)
  Using cached cryptography-42.0.5.tar.gz (671 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Collecting setuptools>=61.0.0
        Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [24 lines of output]
        Traceback (most recent call last):
          File "D:\Program Files\Inkscape\lib\python3.8\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "D:\Program Files\Inkscape\lib\python3.8\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "D:\Program Files\Inkscape\lib\python3.8\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
            self.run_setup()
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\build_meta.py", line 311, in run_setup
            exec(code, locals())
          File "<string>", line 126, in <module>
          File "<string>", line 105, in uses_msvc
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
            self.initialize()
          File "C:\Users\Ali\AppData\Local\Temp\pip-build-env-9tcix642\overlay\lib\python3.8\site-packages\setuptools\_distutils\_msvccompiler.py", line 246, in initialize
            raise DistutilsPlatformError(
        distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

I have spent hours trying to install esptool just for it to give me an unfixable error

**Comment by taku910** [comment] 2024-03-23 12:52
It does not appear to be an error caused by sentencepiece.  This error message doesn't contain the keyword sentencepiece. Please provide details.

**Comment by taku910** [comment] 2024-08-16 15:00
Let me close this bug, as there is no further information provided.

**Closed by taku910** 2024-08-16 15:00 UTC
