### ISSUE TITLE
Using --minloglevel argument in v0.1.90+ causes an error

### ISSUE THREAD

**Issue by jasonnance** [google/sentencepiece#492] opened 2020-05-22 12:54 UTC
I'm calling `spm_train` via the Python wrapper like so:

```python
# Actual parameters differ -- these are just for the example
texts = ["test", "test2"]
model_path = "/tmp/spm"
vocab_size = 30

with tempfile.NamedTemporaryFile(mode="w") as f:
    f.write("\n".join(texts))
    f.flush()

    spm.SentencePieceTrainer.train(
        f"--input={f.name} --model_prefix={model_path} --vocab_size={vocab_size} --minloglevel=2"
    )
```

Since v0.1.90 (still works up to v0.1.86, the last version until then on PyPI), I get the following error back from spm_train:

```
Not found: unknown field name "minloglevel" in TrainerSpec.
```

Is this a regression or do I need to change my invocation to account for changes in v0.1.90?  Thanks!

**Comment by taku910** [comment] 2020-05-24 02:22
Confirmed. Fixed in the head.

**Comment by taku910** [comment] 2020-06-08 16:24
Fixed in v0.1.92.  New pip package is also available.

**Comment by zerotosingularity** [comment] 2020-06-17 09:47
The v0.1.92 package seems to be 'yanked' from pypi.org. Is there a workaround or eta on the new version?

**Comment by jph00** [comment] 2020-09-15 11:52
@taku910 would you be able to provide a status update on providing a new pypi build?

(If there's a blocker that the community might be able to help with, could you let us know what it is, and hopefully someone might be able to provide a PR to help sort it out.)

**Comment by taku910** [comment] 2020-10-14 05:07
Fixed it in v0.19.3

**Closed by taku910** 2020-10-14 05:07 UTC

**Comment by jph00** [comment] 2020-10-14 17:43
@taku910 FYI I don't see it on pypi yet.
