### ISSUE TITLE
/sentencepiece_1581963804834/work/src/trainer_interface.cc(336) [!sentences_.empty()] 

### ISSUE THREAD

**Issue by puraminy** [google/sentencepiece#517] opened 2020-07-03 17:26 UTC
I got this error when trying [MultiFit](https://github.com/n-waves/multifit/tree/pretrain-lm) project for Japanese language:

/sentencepiece_1581963804834/work/src/trainer_interface.cc(336) [!sentences_.empty()] 

full trace:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-c6148ace86c3> in <module>
----> 1 exp.pretrain_lm.train_(wiki_dataset)

~/multifit/multifit/training.py in train_(self, dataset_or_path, tokenizer, **train_config)
    277         print("get_learner call")
    278         print("creating data_lm")
--> 279         data_lm=dataset.load_lm_databunch(bs=self.bs, bptt=self.bptt, limit=self.limit)
    280         # import sys
    281         # sys.exit()

~/multifit/multifit/datasets/dataset.py in load_lm_databunch(self, bs, bptt, limit)
    207                                               bptt=bptt,
    208                                               bs=bs,
--> 209                                               limit=limit)
    210 
    211         with (self.cache_path / "itos.pkl").open('wb') as f:

~/multifit/multifit/datasets/dataset.py in load_n_cache_databunch(self, name, bunch_class, data_loader, bs, limit, **args)
    260                 train_df = train_df[:limit]
    261                 valid_df = valid_df[:limit]
--> 262             databunch = self.databunch_from_df(bunch_class, train_df, valid_df, **args)
    263             print("name:", name)
    264             databunch.save(name)

~/multifit/multifit/datasets/dataset.py in databunch_from_df(self, bunch_class, train_df, valid_df, **args)
    275                                             mark_fields=True,
    276                                             text_cols=list(train_df.columns.values)[1:],
--> 277                                             **args)
    278         return databunch
    279 

~/multifit/fastai_contrib/text_data.py in make_data_bunch_from_df(cls, path, train_df, valid_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, processor, **kwargs)
    160     if cls == TextLMDataBunch:
    161         print("cls == TextLMDataBunch")
--> 162         src = src.label_for_lm().databunch(bs=128)
    163     else:
    164         print("else of cls == TextLMDataBunch")

~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in _inner(*args, **kwargs)
    482             self.valid = fv(*args, from_item_lists=True, **kwargs)
    483             self.__class__ = LabelLists
--> 484             self.process()
    485             return self
    486         return _inner

~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in process(self)
    536         "Process the inner datasets."
    537         xp,yp = self.get_processors()
--> 538         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    539         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    540         for ds in self.lists:

~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in process(self, xp, yp, name, max_warn_items)
    716                     p.warns = []
    717                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 718         self.x.process(xp)
    719         return self
    720 

~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in process(self, processor)
     82         if processor is not None: self.processor = processor
     83         self.processor = listify(self.processor)
---> 84         for p in self.processor: p.process(self)
     85         return self
     86 

~/multifit/fastai_contrib/text_data.py in process(self, ds)
    122 class SPProcessor2(SPProcessor):
    123     def process(self, ds):
--> 124         super().process(ds)
    125         ds.vocab.sp_model = self.sp_model
    126         ds.vocab.sp_vocab = self.sp_vocab

~/miniconda3/lib/python3.7/site-packages/fastai/text/data.py in process(self, ds)
    467                     for t in progress_bar(ds.items, leave=False)]
    468         if self.sp_model is None or self.sp_vocab is None:
--> 469             cache_dir = self.train_func(ds.items, ds.path)
    470             self.sp_model,self.sp_vocab = cache_dir/'spm.model',cache_dir/'spm.vocab'
    471         if not getattr(self, 'vocab', False):

~/miniconda3/lib/python3.7/site-packages/fastai/text/data.py in train_sentencepiece(texts, path, pre_rules, post_rules, vocab_sz, max_vocab_sz, model_type, max_sentence_len, lang, char_coverage, tmp_dir, enc)
    437         f"--user_defined_symbols={','.join(spec_tokens)}",
    438         # f"--model_prefix={quotemark}{cache_dir/'spm'}{quotemark} --hard_vocab_limit=false --vocab_size={vocab_sz} --model_type={model_type}"]))
--> 439         f"--model_prefix={quotemark}{cache_dir/'spm'}{quotemark} --vocab_size={vocab_sz} --model_type={model_type}"]))
    440     raw_text_path.unlink()
    441     return cache_dir

RuntimeError: Internal: /home/conda/feedstock_root/build_artifacts/sentencepiece_1581963804834/work/src/trainer_interface.cc(336) [!sentences_.empty()] 

`

**Comment by fabero** [comment] 2020-07-27 13:19
Does anyone know what the cause of this is? I encountered the same issue when trying to train on rather long (~4000 words) texts.

**Comment by sinaahmadi** [comment] 2020-08-04 16:31
I have the very same issue with `word` model.

**Comment by sinaahmadi** [comment] 2020-08-04 17:24
Something that may help solving this problem. Check how many lines your corpus has, i.e. `wc -l`. I had the same issue and then I found out that when I had merged my corpora, all the newlines where removed!

**Comment by conquerSelf** [comment] 2020-09-01 03:53
i meet the same problem,have you solved it?i need useful suggestion.Than you!

**Comment by Masao-Taketani** [comment] 2020-10-11 14:07
I had the similar error, which says "RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(407) [!sentences_.empty()]".
If you have the above problem, make that you need to have one sentence per line according to the document.
That's how I solved the above issue.
[reference] https://github.com/google/sentencepiece#train-sentencepiece-model

**Comment by stephantul** [comment] 2020-10-20 12:28
@fabero The problem is likely that all of your lines are too long, just raise `--max_sentence_length` to an appropriate number, or segment your texts into shorter pieces.

**Comment by taku910** [comment] 2020-12-28 16:44
This error happens when all of input lines are too long. Please increase the length via `--max_sentence_length`

**Closed by taku910** 2020-12-28 16:44 UTC

**Comment by vvbreak** [comment] 2021-02-22 03:09
I got the exact same error as you.
Probably the path in the corpus is not correct.
In my case, I used a relative path (. /path/to/your/corpus.txt), I was able to create "vocab.txt".

**Comment by aixuedegege** [comment] 2021-05-21 08:19
the list parameter "user_defined_symbols" you passed cannot contain empty strings.
